### ISSUE TITLE
Provide source package on PyPI or precompiled packages for M1 MacBooks

### ISSUE THREAD

**Issue by niklasb** [ethereum/blake2b-py#7]
Similar to https://github.com/ethereum/blake2b-py/issues/1, since 0.1.4 does not provide a source package, it cannot be installed on M1 MacBooks currently:

```sh
$ pip install 'blake2b-py==1.4.0'
ERROR: Could not find a version that satisfies the requirement blake2b-py==1.4.0
ERROR: No matching distribution found for blake2b-py==1.4.0
```

This is an issue, since it is a dependency of py-evm

**Comment by yorhodes** [comment]
I was able to fix this by adding 
```
blake2b-py = { git = "https://github.com/ethereum/blake2b-py.git", tag="v0.1.4" }
```
to my `pyproject.toml`

**Comment by mattslipari** [comment]
@yorhodes Where in `pyprojec.toml` did you add this line?

**Comment by MT-Cash** [comment]
@mattslipari Something like this:

```
[tool.poetry.dev-dependencies]
blake2b-py = { git = "https://github.com/ethereum/blake2b-py.git", tag="v0.1.4" }
```

**Comment by MT-Cash** [comment]
@cburgdorf What do you think about uploading a source package?

**Comment by 0xTimepunk** [comment]
@cburgdorf seconding the above

**Comment by foufrix** [comment]
This issue is solved no?
Just installed [Mythril](https://github.com/ConsenSys/mythril) that used `blake2b-py`; the only thing needed is to install a nightly version of rust for it to install properly

**Comment by MT-Cash** [comment]
I only see Wheel pacakges here https://pypi.org/project/blake2b-py/#files

It's not solved. But it would be easy to solve for the maintainer.
